[project]
name = "kube-custom-resource"
description = "Utilities for working with Kubernetes custom resources."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
dynamic = ["version"]
dependencies = [
    "annotated-types>=0.8.0",
    "click>=8.4.2",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.3,<0.17",
    "coverage>=7.15.4",
    "python-subunit>=1.4.6",
    "stestr>=4.2.1",
    "testtools>=2.9.1",
    "codespell>=2.4.3",
    "autopep8>=2.3.2",
    "mypy>=2.3.1",
    "types-pyyaml>=6.0.12.20260815",
    "tox>=4.60.0",
    "tox-uv>=1.36.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "black>=26.5.1",
]

# We use hatchling instead of uv's own build backend because UV does not have a way to dynamically get the version from git.
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.1+unknown"

[project.scripts]
kcr_generate = "kube_custom_resource.generate:main"

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-builtins
    "A",
    # Ruff rules
    "RUF",
    # flake8-async
    "ASYNC",
    # pyupgrade
    "UP",
    # tidy imports
    "TID",
    # sorted imports
    "I",
    # check complexity
    "C90",
    # pep8 naming
    "N",
]
ignore = [
    "UP017", # remove and fix once 3.10 no longer tested in CI
]

[tool.mypy]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true

[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 15
