[tox]
env_list = clean,report,py310,black,ruff,codespell,autofix

[testenv]
description = run unit tests
runner = uv-venv-lock-runner
usedevelop = True
commands = pytest --cov=kube_custom_resource --cov-report= -vv --color=yes
depends =
    py310: clean
    report: py310

[testenv:report]
commands =
    coverage report
    coverage html -d cover
    coverage xml -o cover/coverage.xml

[testenv:clean]
commands = coverage erase

[testenv:autofix]
commands =
    ruff format {tox_root}
    codespell --skip "./cover/*," -w
    ruff check {tox_root} --fix

[testenv:black]
commands = black --check --diff {tox_root} {posargs}

[testenv:codespell]
commands = codespell --skip "./cover/*" {posargs}

[testenv:ruff]
description = Run Ruff checks
commands =
    ruff check {tox_root}
    ruff format {tox_root} --check

[testenv:mypy]
commands = mypy kube_custom_resource
